---
- name: apt-get update
  become: true
  apt:
    update_cache: yes

- name: apt-get install collectd
  become: true
  apt:
    name: collectd

- name: apt-get install collectd
  become: true
  apt:
    name: collectd-utils